version: '3.8'
services:
  eula-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eula-api
    hostname: eula-api
    tty: true
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    environment:
      - APP_KEY=1234567890
    ports:
      - "5000:5000"
    stdin_open: true
    links:
      - eula-db
    depends_on:
      - eula-db
    networks:
      - node-webapp-network
  
  eula-db:
    container_name: eula-db
    image: mongo:4.4.6
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - node-webapp-network

networks:
  node-webapp-network:
    driver: bridge
