name: eslint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn lint